services:
  - type: web
    name: edu-institute-frontend
    buildCommand: "npm run build"
    startCommand: "npm start"
    envVars:
      - key: NODE_VERSION
        value: "16.x"  # Set Node version to 16.x
